export const userFields = {
    details: {
        title: "Details",
        align: "center",
        render: false,
        type: "boolean",
        searchable: false,
    },
    active: {
        title: "Active Status",
        align: "center",
        render: false,
        type: "boolean",
        searchable: true,
    },
    name: {
        title: "User Name",
        align: "left",
        render: true,
        register: true,
        type: "text",
        searchable: true,
    },
    age: {
        title: "Age",
        align: "center",
        render: true,
        register: true,
        short: true,
        type: "number",
        searchable: true,
        searchedBy: [
            { key: "minAge", title: "Min Age" },
            { key: "maxAge", title: "Max Age" },
        ],
    },
    passportId: {
        title: "Passport ID",
        align: "right",
        render: true,
        register: true,
        short: true,
        type: "text",
        searchable: true,
    },
    email: {
        title: "Email",
        align: "center",
        render: true,
        register: true,
        type: "email",
        searchable: true,
    },
    totalCash: {
        title: "Total Cash",
        align: "right",
        render: true,
        type: "number",
        searchable: true,
        searchedBy: [
            { key: "minCash", title: "Min Cash" },
            { key: "maxCash", title: "Max Cash" },
        ],
    },
    totalCredit: {
        title: "Total Credit",
        align: "right",
        render: true,
        type: "number",
        searchable: true,
        searchedBy: [
            { key: "minCredit", title: "Min Credit" },
            { key: "maxCredit", title: "Max Credit" },
        ],
    },
    createdAt: {
        title: "Registration Date",
        align: "right",
        render: true,
        type: "number",
        searchable: false,
    },
};

export const accountFields = {
    details: {
        title: "Details",
        align: "center",
        render: false,
        type: "boolean",
        searchable: false,
    },
    id: {
        title: "Account ID",
        align: "right",
        render: true,
        type: "text",
        actions: [
            {
                key: "userSearch",
                title: "Search User (Passport ID or Email)",
                hideButton: "true",
            },
            {
                key: "accountId",
                title: "Choose Account",
                hideButton: "true",
                type: "autocomplete",
            },
            { key: "transaction", title: "Send Amount" },
        ],
    },
    cash: {
        title: "Cash",
        align: "right",
        render: true,
        type: "number",
        actions: [
            { key: "withdrawCash", title: "Withdraw Cash" },
            { key: "updateCash", title: "Deposit Cash" },
        ],
    },
    credit: {
        title: "Credit",
        align: "right",
        render: true,
        type: "number",
        actions: [
            { key: "withdrawCredit", title: "Increase Credit" },
            { key: "updateCredit", title: "Decrease Credit" },
        ],
    },
    createdAt: {
        title: "Account Opening Date",
        align: "right",
        render: true,
        type: "date",
    },
    updatedAt: {
        title: "Last Transaction",
        align: "right",
        render: true,
        type: "date",
    },
};
