export const userFields = {
    details: {
        title: "Details",
        align: "center",
        display: false,
        registerFormDisplay: false,
        short: false,
        type: "boolean",
        searchable: false,
    },
    active: {
        title: "Active Status",
        align: "center",
        display: false,
        registerFormDisplay: false,
        short: false,
        type: "boolean",
        searchable: true,
    },
    name: {
        title: "User Name",
        align: "left",
        display: true,
        registerFormDisplay: true,
        short: false,
        type: "text",
        searchable: true,
    },
    age: {
        title: "Age",
        align: "center",
        display: true,
        registerFormDisplay: true,
        short: true,
        short: false,
        type: "number",
        searchable: true,
        searchedBy: [
            { key: "minAge", title: "Min Age" },
            { key: "maxAge", title: "Max Age" },
        ],
    },
    passportId: {
        title: "Passport ID",
        align: "right",
        display: true,
        registerFormDisplay: true,
        short: true,
        short: false,
        type: "text",
        searchable: true,
    },
    email: {
        title: "Email",
        align: "center",
        display: true,
        registerFormDisplay: true,
        short: false,
        type: "email",
        searchable: true,
    },
    totalCash: {
        title: "Total Cash",
        align: "right",
        display: true,
        registerFormDisplay: false,
        short: false,
        type: "number",
        searchable: true,
        searchedBy: [
            { key: "minCash", title: "Min Cash" },
            { key: "maxCash", title: "Max Cash" },
        ],
    },
    totalCredit: {
        title: "Total Credit",
        align: "right",
        display: true,
        registerFormDisplay: false,
        short: false,
        type: "number",
        searchable: true,
        searchedBy: [
            { key: "minCredit", title: "Min Credit" },
            { key: "maxCredit", title: "Max Credit" },
        ],
    },
    createdAt: {
        title: "Registration Date",
        align: "right",
        display: true,
        registerFormDisplay: false,
        short: false,
        type: "number",
        searchable: false,
    },
};

export const accountFields = {
    details: {
        title: "Details",
        align: "center",
        display: false,
        type: "boolean",
        searchable: false,
    },
    id: {
        title: "Account ID",
        align: "right",
        display: true,
        type: "text",
        searchable: false,
        actions: [
            {
                title: "Search User (Passport ID or Email)",
                key: "setTransactionUser",
                type: "text",
                hideButton: true,
            },
            {
                title: "Choose Account",
                key: "setTransactionAccount",
                type: "text",
                hideButton: true,
            },
            {
                title: "Send Amount",
                key: "setTransactionAmount",
                type: "number",
                hideButton: false,
            },
        ],
    },
    cash: {
        title: "Cash",
        align: "right",
        display: true,
        type: "number",
        searchable: false,
        actions: [
            {
                title: "Withdraw Cash Amount",
                key: "withdrawCash",
                type: "number",
                hideButton: false,
            },
            {
                title: "Deposit Cash Amount",
                key: "depositCash",
                type: "number",
                hideButton: false,
            },
        ],
    },
    credit: {
        title: "Credit",
        align: "right",
        display: true,
        type: "number",
        searchable: false,
        actions: [
            {
                title: "Increase Credit Amount",
                key: "increaseCredit",
                type: "number",
                hideButton: false,
            },
            {
                title: "Decrease Credit Amount",
                key: "decreaseCredit",
                type: "number",
                hideButton: false,
            },
        ],
    },
    createdAt: {
        title: "Account Opening Date",
        align: "right",
        display: true,
        type: "date",
        searchable: false,
    },
    updatedAt: {
        title: "Last Transaction",
        align: "right",
        display: true,
        type: "date",
        searchable: false,
    },
};
